
services:
  app:
    image: smart-feedback-app
    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://db:3306/feedback_db
      DB_USERNAME: feedback_user
      DB_PASSWORD: feedback_pass
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: prod
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: feedback_db
      MYSQL_USER: feedback_user
      MYSQL_PASSWORD: feedback_pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7